In [1]:
import yfinance as yf
import os

# Fetch data for a specific stock by downloading market data from Yahoo, Finance's API

ticker = 'AMZN'
amazon = yf.download(ticker, start="1980-01-01", end="2024-9-30")
print(amazon)

[*********************100%***********************]  1 of 1 completed

                  Open        High         Low       Close   Adj Close  \
Date
1997-05-15    0.121875    0.125000    0.096354    0.097917    0.097917
1997-05-16    0.098438    0.098958    0.085417    0.086458    0.086458
1997-05-19    0.088021    0.088542    0.081250    0.085417    0.085417
1997-05-20    0.086458    0.087500    0.081771    0.081771    0.081771
1997-05-21    0.081771    0.082292    0.068750    0.071354    0.071354
...                ...         ...         ...         ...         ...
2024-09-23  191.639999  194.449997  190.570007  193.880005  193.880005
2024-09-24  194.270004  195.369995  190.130005  193.960007  193.960007
2024-09-25  193.750000  193.949997  192.160004  192.529999  192.529999
2024-09-26  194.309998  194.529999  189.539993  191.160004  191.160004
2024-09-27  190.679993  190.899994  187.339996  187.970001  187.970001

                Volume
Date
1997-05-15  1443120000
1997-05-16   294000000
1997-05-19   122136000
1997-05-20   109344000
1997-05-21   377064000
...                ...
2024-09-23    36993100
2024-09-24    43478900
2024-09-25    26391100
2024-09-26    36334900
2024-09-27    36002300

[6888 rows x 6 columns]

In [2]:
ticker = 'AAPL'
apple = yf.download(ticker, start="1980-01-01", end="2024-9-30")
print(apple)

[*********************100%***********************]  1 of 1 completed

                  Open        High         Low       Close   Adj Close  \
Date
1980-12-12    0.128348    0.128906    0.128348    0.128348    0.098943
1980-12-15    0.122210    0.122210    0.121652    0.121652    0.093781
1980-12-16    0.113281    0.113281    0.112723    0.112723    0.086898
1980-12-17    0.115513    0.116071    0.115513    0.115513    0.089049
1980-12-18    0.118862    0.119420    0.118862    0.118862    0.091630
...                ...         ...         ...         ...         ...
2024-09-23  227.339996  229.449997  225.809998  226.470001  226.470001
2024-09-24  228.649994  229.350006  225.729996  227.369995  227.369995
2024-09-25  224.929993  227.289993  224.020004  226.369995  226.369995
2024-09-26  227.300003  228.500000  225.410004  227.520004  227.520004
2024-09-27  228.460007  229.520004  227.300003  227.789993  227.789993

               Volume
Date
1980-12-12  469033600
1980-12-15  175884800
1980-12-16  105728000
1980-12-17   86441600
1980-12-18   73449600
...               ...
2024-09-23   54146000
2024-09-24   43556100
2024-09-25   42308700
2024-09-26   36636700
2024-09-27   34026000

[11040 rows x 6 columns]

In [3]:
ticker = 'META'
meta = yf.download(ticker, start="1980-01-01", end="2024-9-30")
print(meta)

[*********************100%***********************]  1 of 1 completed

                  Open        High         Low       Close   Adj Close  \
Date
2012-05-18   42.049999   45.000000   38.000000   38.230000   38.115242
2012-05-21   36.529999   36.660000   33.000000   34.029999   33.927845
2012-05-22   32.610001   33.590000   30.940001   31.000000   30.906942
2012-05-23   31.370001   32.500000   31.360001   32.000000   31.903940
2012-05-24   32.950001   33.209999   31.770000   33.029999   32.930847
...                ...         ...         ...         ...         ...
2024-09-23  569.500000  573.979980  562.409973  564.409973  564.409973
2024-09-24  566.679993  567.750000  554.190002  563.330017  563.330017
2024-09-25  564.049988  576.880005  563.719971  568.309998  568.309998
2024-09-26  575.729980  577.400024  562.349976  567.840027  567.840027
2024-09-27  570.099976  570.840027  564.510010  567.359985  567.359985

               Volume
Date
2012-05-18  573576400
2012-05-21  168192700
2012-05-22  101786600
2012-05-23   73600000
2012-05-24   50237200
...               ...
2024-09-23   12830700
2024-09-24   12993000
2024-09-25   16543400
2024-09-26   14400800
2024-09-27    9398400

[3110 rows x 6 columns]

In [4]:
ticker = 'MSFT'
microsoft = yf.download(ticker, start="1980-01-01", end="2024-9-30")
print(microsoft)

[*********************100%***********************]  1 of 1 completed

                  Open        High         Low       Close   Adj Close  \
Date
1986-03-13    0.088542    0.101563    0.088542    0.097222    0.059947
1986-03-14    0.097222    0.102431    0.097222    0.100694    0.062087
1986-03-17    0.100694    0.103299    0.100694    0.102431    0.063158
1986-03-18    0.102431    0.103299    0.098958    0.099826    0.061552
1986-03-19    0.099826    0.100694    0.097222    0.098090    0.060482
...                ...         ...         ...         ...         ...
2024-09-23  434.279999  436.459991  430.390015  433.510010  433.510010
2024-09-24  433.000000  433.350006  426.100006  429.170013  429.170013
2024-09-25  429.829987  433.119995  428.570007  432.109985  432.109985
2024-09-26  435.089996  435.299988  429.130005  431.309998  431.309998
2024-09-27  431.519989  431.850006  427.470001  428.019989  428.019989

                Volume
Date
1986-03-13  1031788800
1986-03-14   308160000
1986-03-17   133171200
1986-03-18    67766400
1986-03-19    47894400
...                ...
2024-09-23    15128900
2024-09-24    17015800
2024-09-25    13396400
2024-09-26    14492000
2024-09-27    14896100

[9714 rows x 6 columns]

In [5]:
ticker = 'NFLX'
netflix = yf.download(ticker, start="1980-01-01", end="2024-9-30")
print(netflix)

[*********************100%***********************]  1 of 1 completed

                  Open        High         Low       Close   Adj Close  \
Date
2002-05-23    1.156429    1.242857    1.145714    1.196429    1.196429
2002-05-24    1.214286    1.225000    1.197143    1.210000    1.210000
2002-05-28    1.213571    1.232143    1.157143    1.157143    1.157143
2002-05-29    1.164286    1.164286    1.085714    1.103571    1.103571
2002-05-30    1.107857    1.107857    1.071429    1.071429    1.071429
...                ...         ...         ...         ...         ...
2024-09-23  702.390015  712.250000  699.159973  705.369995  705.369995
2024-09-24  706.630005  722.440002  704.450012  722.260010  722.260010
2024-09-25  721.000000  725.119995  716.210022  721.559998  721.559998
2024-09-26  724.729980  725.260010  701.719971  711.429993  711.429993
2024-09-27  708.359985  710.710022  701.250000  707.349976  707.349976

               Volume
Date
2002-05-23  104790000
2002-05-24   11104800
2002-05-28    6609400
2002-05-29    6757800
2002-05-30   10154200
...               ...
2024-09-23    3224300
2024-09-24    3565700
2024-09-25    2259800
2024-09-26    2833000
2024-09-27    2395600

[5626 rows x 6 columns]

In [6]:
ticker = 'TSLA'
tesla = yf.download(ticker, start="1980-01-01", end="2024-9-30")
print(tesla)

[*********************100%***********************]  1 of 1 completed

                  Open        High         Low       Close   Adj Close  \
Date
2010-06-29    1.266667    1.666667    1.169333    1.592667    1.592667
2010-06-30    1.719333    2.028000    1.553333    1.588667    1.588667
2010-07-01    1.666667    1.728000    1.351333    1.464000    1.464000
2010-07-02    1.533333    1.540000    1.247333    1.280000    1.280000
2010-07-06    1.333333    1.333333    1.055333    1.074000    1.074000
...                ...         ...         ...         ...         ...
2024-09-23  242.610001  250.000000  241.919998  250.000000  250.000000
2024-09-24  254.080002  257.190002  249.050003  254.270004  254.270004
2024-09-25  252.539993  257.049988  252.279999  257.019989  257.019989
2024-09-26  260.600006  261.750000  251.529999  254.220001  254.220001
2024-09-27  257.380005  260.700012  254.119995  260.459991  260.459991

               Volume
Date
2010-06-29  281494500
2010-06-30  257806500
2010-07-01  123282000
2010-07-02   77097000
2010-07-06  103003500
...               ...
2024-09-23   86927200
2024-09-24   88491000
2024-09-25   65034300
2024-09-26   67142200
2024-09-27   70988100

[3587 rows x 6 columns]

In [7]:
# Exporting downloaded data to csvs
path = r'/Users/matthewabrams/Desktop/Stocks Data/Stock Datasets/'

amazon.to_csv(os.path.join(path, 'Original Stock Data', 'HistoricalData_Amazon.csv'))
apple.to_csv(os.path.join(path, 'Original Stock Data', 'HistoricalData_Apple.csv'))
meta.to_csv(os.path.join(path, 'Original Stock Data', 'HistoricalData_Meta.csv'))
microsoft.to_csv(os.path.join(path, 'Original Stock Data', 'HistoricalData_Microsoft.csv'))
netflix.to_csv(os.path.join(path, 'Original Stock Data', 'HistoricalData_Netflix.csv'))
tesla.to_csv(os.path.join(path, 'Original Stock Data', 'HistoricalData_Tesla.csv'))