In [1]:
import yfinance as yf
import os

# Fetch data for a specific stock by downloading market data from Yahoo, Finance's API

ticker = 'AMZN'
amazon = yf.download(ticker, start="1980-01-01", end="2024-11-15")
print(amazon)

[*********************100%***********************]  1 of 1 completed

                  Open        High         Low       Close   Adj Close  \
Date
1997-05-15    0.121875    0.125000    0.096354    0.097917    0.097917
1997-05-16    0.098438    0.098958    0.085417    0.086458    0.086458
1997-05-19    0.088021    0.088542    0.081250    0.085417    0.085417
1997-05-20    0.086458    0.087500    0.081771    0.081771    0.081771
1997-05-21    0.081771    0.082292    0.068750    0.071354    0.071354
...                ...         ...         ...         ...         ...
2024-11-08  209.720001  209.960007  207.440002  208.179993  208.179993
2024-11-11  208.500000  209.649994  205.589996  206.839996  206.839996
2024-11-12  208.369995  209.539993  206.009995  208.910004  208.910004
2024-11-13  209.399994  215.089996  209.139999  214.100006  214.100006
2024-11-14  214.160004  215.899994  210.880005  211.479996  211.479996

                Volume
Date
1997-05-15  1443120000
1997-05-16   294000000
1997-05-19   122136000
1997-05-20   109344000
1997-05-21   377064000
...                ...
2024-11-08    36075800
2024-11-11    35456000
2024-11-12    38942900
2024-11-13    46212900
2024-11-14    42620300

[6922 rows x 6 columns]

In [2]:
ticker = 'AAPL'
apple = yf.download(ticker, start="1980-01-01", end="2024-11-15")
print(apple)

[*********************100%***********************]  1 of 1 completed

                  Open        High         Low       Close   Adj Close  \
Date
1980-12-12    0.128348    0.128906    0.128348    0.128348    0.098834
1980-12-15    0.122210    0.122210    0.121652    0.121652    0.093678
1980-12-16    0.113281    0.113281    0.112723    0.112723    0.086802
1980-12-17    0.115513    0.116071    0.115513    0.115513    0.088951
1980-12-18    0.118862    0.119420    0.118862    0.118862    0.091530
...                ...         ...         ...         ...         ...
2024-11-08  227.169998  228.660004  226.410004  226.960007  226.960007
2024-11-11  225.000000  225.699997  221.500000  224.229996  224.229996
2024-11-12  224.550003  225.589996  223.360001  224.229996  224.229996
2024-11-13  224.009995  226.649994  222.759995  225.119995  225.119995
2024-11-14  225.020004  228.869995  225.000000  228.220001  228.220001

               Volume
Date
1980-12-12  469033600
1980-12-15  175884800
1980-12-16  105728000
1980-12-17   86441600
1980-12-18   73449600
...               ...
2024-11-08   38328800
2024-11-11   42005600
2024-11-12   40398300
2024-11-13   48566200
2024-11-14   44923900

[11074 rows x 6 columns]

In [3]:
ticker = 'META'
meta = yf.download(ticker, start="1980-01-01", end="2024-11-15")
print(meta)

[*********************100%***********************]  1 of 1 completed

                  Open        High         Low       Close   Adj Close  \
Date
2012-05-18   42.049999   45.000000   38.000000   38.230000   38.115242
2012-05-21   36.529999   36.660000   33.000000   34.029999   33.927845
2012-05-22   32.610001   33.590000   30.940001   31.000000   30.906942
2012-05-23   31.370001   32.500000   31.360001   32.000000   31.903942
2012-05-24   32.950001   33.209999   31.770000   33.029999   32.930851
...                ...         ...         ...         ...         ...
2024-11-08  591.539978  593.099976  584.520020  589.340027  589.340027
2024-11-11  586.359985  587.000000  576.510010  583.169983  583.169983
2024-11-12  588.539978  599.659973  580.380005  584.820007  584.820007
2024-11-13  582.609985  585.640015  575.169983  580.000000  580.000000
2024-11-14  577.000000  580.760010  573.010010  577.159973  577.159973

               Volume
Date
2012-05-18  573576400
2012-05-21  168192700
2012-05-22  101786600
2012-05-23   73600000
2012-05-24   50237200
...               ...
2024-11-08    9415700
2024-11-11   10209100
2024-11-12   16287700
2024-11-13   10757600
2024-11-14   11053700

[3144 rows x 6 columns]

In [4]:
ticker = 'MSFT'
microsoft = yf.download(ticker, start="1980-01-01", end="2024-11-15")
print(microsoft)

[*********************100%***********************]  1 of 1 completed

                  Open        High         Low       Close   Adj Close  \
Date
1986-03-13    0.088542    0.101563    0.088542    0.097222    0.059947
1986-03-14    0.097222    0.102431    0.097222    0.100694    0.062087
1986-03-17    0.100694    0.103299    0.100694    0.102431    0.063158
1986-03-18    0.102431    0.103299    0.098958    0.099826    0.061552
1986-03-19    0.099826    0.100694    0.097222    0.098090    0.060482
...                ...         ...         ...         ...         ...
2024-11-08  425.320007  426.500000  421.779999  422.540009  422.540009
2024-11-11  422.519989  424.809998  416.000000  418.010010  418.010010
2024-11-12  418.250000  424.440002  417.200012  423.029999  423.029999
2024-11-13  421.640015  429.329987  418.209991  425.200012  425.200012
2024-11-14  425.000000  428.170013  420.000000  426.890015  426.890015

                Volume
Date
1986-03-13  1031788800
1986-03-14   308160000
1986-03-17   133171200
1986-03-18    67766400
1986-03-19    47894400
...                ...
2024-11-08    16891400
2024-11-11    24503300
2024-11-12    19401200
2024-11-13    21502200
2024-11-14    30246900

[9748 rows x 6 columns]

In [5]:
ticker = 'NFLX'
netflix = yf.download(ticker, start="1980-01-01", end="2024-11-15")
print(netflix)

[*********************100%***********************]  1 of 1 completed

                  Open        High         Low       Close   Adj Close  \
Date
2002-05-23    1.156429    1.242857    1.145714    1.196429    1.196429
2002-05-24    1.214286    1.225000    1.197143    1.210000    1.210000
2002-05-28    1.213571    1.232143    1.157143    1.157143    1.157143
2002-05-29    1.164286    1.164286    1.085714    1.103571    1.103571
2002-05-30    1.107857    1.107857    1.071429    1.071429    1.071429
...                ...         ...         ...         ...         ...
2024-11-08  797.359985  799.059998  788.650024  795.039978  795.039978
2024-11-11  795.900024  806.820007  795.570007  805.440002  805.440002
2024-11-12  807.500000  820.369995  803.750000  819.500000  819.500000
2024-11-13  822.619995  836.989990  820.539978  830.469971  830.469971
2024-11-14  833.669983  841.000000  830.020020  837.260010  837.260010

               Volume
Date
2002-05-23  104790000
2002-05-24   11104800
2002-05-28    6609400
2002-05-29    6757800
2002-05-30   10154200
...               ...
2024-11-08    1910600
2024-11-11    2399200
2024-11-12    2814100
2024-11-13    2767800
2024-11-14    3038200

[5660 rows x 6 columns]

In [6]:
ticker = 'TSLA'
tesla = yf.download(ticker, start="1980-01-01", end="2024-11-15")
print(tesla)

[*********************100%***********************]  1 of 1 completed

                  Open        High         Low       Close   Adj Close  \
Date
2010-06-29    1.266667    1.666667    1.169333    1.592667    1.592667
2010-06-30    1.719333    2.028000    1.553333    1.588667    1.588667
2010-07-01    1.666667    1.728000    1.351333    1.464000    1.464000
2010-07-02    1.533333    1.540000    1.247333    1.280000    1.280000
2010-07-06    1.333333    1.333333    1.055333    1.074000    1.074000
...                ...         ...         ...         ...         ...
2024-11-08  299.140015  328.709991  297.660004  321.220001  321.220001
2024-11-11  346.299988  358.640015  336.000000  350.000000  350.000000
2024-11-12  342.739990  345.839996  323.309998  328.489990  328.489990
2024-11-13  335.850006  344.600006  322.500000  330.239990  330.239990
2024-11-14  327.690002  329.980011  310.369995  311.179993  311.179993

               Volume
Date
2010-06-29  281494500
2010-06-30  257806500
2010-07-01  123282000
2010-07-02   77097000
2010-07-06  103003500
...               ...
2024-11-08  204782800
2024-11-11  210521600
2024-11-12  155726000
2024-11-13  125405600
2024-11-14  120726100

[3621 rows x 6 columns]

In [7]:
# Exporting downloaded data to csvs
path = r'/Users/matthewabrams/Desktop/Stocks Data/Stock Datasets/'

amazon.to_csv(os.path.join(path, 'Original Stock Data', 'HistoricalData_Amazon.csv'))
apple.to_csv(os.path.join(path, 'Original Stock Data', 'HistoricalData_Apple.csv'))
meta.to_csv(os.path.join(path, 'Original Stock Data', 'HistoricalData_Meta.csv'))
microsoft.to_csv(os.path.join(path, 'Original Stock Data', 'HistoricalData_Microsoft.csv'))
netflix.to_csv(os.path.join(path, 'Original Stock Data', 'HistoricalData_Netflix.csv'))
tesla.to_csv(os.path.join(path, 'Original Stock Data', 'HistoricalData_Tesla.csv'))